#!/bin/sh

ASCII_FIFO=/run/ascii-conv-in
XY_FIFO=/run/pnt-lut-xy
PGM_FIFO=/run/pnt-lut-pgm
HAPTIC_FIFO=/run/haptic-in
SIGCOMP_FIFO=/run/sigcomp-in
SIGPROC_FIFO=/run/sigproc-in
OSCOPE_FIFO=/run/oscope-in

# make fifos. linearly
mkfifo $ASCII_FIFO
mkfifo $XY_FIFO
mkfifo $PGM_FIFO
mkfifo $HAPTIC_FIFO
mkfifo $SIGCOMP_FIFO
mkfifo $SIGPROC_FIFO
mkfifo $OSCOPE_FIFO

enable-haptic-gpio

# start programs in background

# "left side" of tree

pipe-wrapper "trigger-data -i /dev/stdin -o /dev/stdout" $OSCOPE_FIFO $SIGPROC_FIFO &

pipe-wrapper "sigproc -i /dev/stdin -o /dev/stdout" $SIGPROC_FIFO $SIGCOMP_FIFO &

pipe-wrapper "signal-compiler /dev/stdin /dev/stdout" $SIGCOMP_FIFO $PGM_FIFO &

wacom-btn > $OSCOPE_FIFO &

# "right side" of tree
haptic-driver $HAPTIC_FIFO &

pnt-lut $PGM_FIFO $XY_FIFO $HAPTIC_FIFO &

ascii-conv $ASCII_FIFO $XY_FIFO &


pnt-lut $PGM_FIFO $XY_FIFO $HAPTIC_FIFO &

wacom-xy > $ASCII_FIFO &
